name: example
version: 1.2.0
description: Complete email service with SMTP support, templates, and queue management
author: arlomu
license: MIT
repository: https://github.com/tontoo-packages/example.git

dependencies:
  - nodemailer: "^6.9.0"
  - mustache: "^4.2.0"

scripts:
  postinstall: "npm install nodemailer mustache"
  preuninstall: "echo 'Cleaning up email service...'"

tontoo:
  minVersion: "1.8.0"
  type: "service"
  
keywords:
  - email
  - smtp
  - templates
  - notifications
